### PR TITLE
Fix build on ARM

### LINKED ISSUE #4: Do not compile to arm
Hello,

I was hoping to use this library for a project on a raspberry pi but it doesn't compile, it give me this error :

```
cargo build --target=armv7-unknown-linux-gnueabihf
   Compiling interfaces v0.0.1 (file:///home/neodc/tmp/interfaces-rs)
error[E0308]: mismatched types
   --> src/lib.rs:389:45
    |
389 |         let res = unsafe { ioctl(self.sock, SIOCGIFHWADDR, &mut req) };
    |                                             ^^^^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error[E0308]: mismatched types
   --> src/lib.rs:400:64
    |
400 |         let addr = unsafe { mem::transmute::<[i8; 6], [u8; 6]>(addr) };
    |                                                                ^^^^ expected i8, found u8

error[E0308]: mismatched types
   --> src/lib.rs:476:45
    |
476 |         let res = unsafe { ioctl(self.sock, SIOCGIFFLAGS, &mut req) };
    |                                             ^^^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error[E0308]: mismatched types
   --> src/lib.rs:494:45
    |
494 |         let res = unsafe { ioctl(self.sock, SIOCSIFFLAGS, &mut req) };
    |                                             ^^^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error[E0308]: mismatched types
   --> src/lib.rs:520:45
    |
520 |         let res = unsafe { ioctl(self.sock, SIOCGIFMTU, &mut req) };
    |                                             ^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error: aborting due to 5 previous errors

error: Could not compile `interfaces`.
```

### PR DESCRIPTION
**Pull request by andrew-d**
Closes #4

### CODE REVIEW

**Comment by andrew-d** [comment]
Confirmed that this now builds on ARM using: https://github.com/dlecan/rust-crosscompiler-arm

```
docker run -it --rm \
  -v $(pwd):/source \
  dlecan/rust-crosscompiler-arm:stable
```

**Comment by neodc** [comment]
Would it be possible to tag a new release with this patch? For the moment it seems I have to use the git repository as a source to have this fix.

**Comment by andrew-d** [comment]
Sure!  Just tagged and released version 0.0.2 😄

**Comment by prisme60** [comment]
Sorry  but it still not compile for me for version 0.0.3 on raspberry pi : 
````bash
pi@rp1 ~/rust/intf $ cargo run
   Compiling interfaces v0.0.3
error[E0308]: mismatched types
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/interfaces-0.0.3/src/lib.rs:389:45
    |
389 |         let res = unsafe { ioctl(self.sock, SIOCGIFHWADDR, &mut req) };
    |                                             ^^^^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error[E0308]: mismatched types
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/interfaces-0.0.3/src/lib.rs:476:45
    |
476 |         let res = unsafe { ioctl(self.sock, SIOCGIFFLAGS, &mut req) };
    |                                             ^^^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error[E0308]: mismatched types
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/interfaces-0.0.3/src/lib.rs:494:45
    |
494 |         let res = unsafe { ioctl(self.sock, SIOCSIFFLAGS, &mut req) };
    |                                             ^^^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error[E0308]: mismatched types
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/interfaces-0.0.3/src/lib.rs:520:45
    |
520 |         let res = unsafe { ioctl(self.sock, SIOCGIFMTU, &mut req) };
    |                                             ^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error: aborting due to 4 previous errors
```

I have the following versions :
```bash
pi@rp1 ~/rust/intf $ cargo --version
cargo 0.23.0 (61fa02415 2017-11-22)
pi@rp1 ~/rust/intf $ rustc --version
rustc 1.22.1 (05e2e1c41 2017-11-22)
pi@rp1 ~/rust/intf $ uname -a
Linux rp1 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
pi@rp1 ~/rust/intf $ rustup --version
rustup 1.7.0 (813f7b7a8 2017-10-30)
```

**Pull request merged**
